# Enables the custom SkriptPlus error messages.
# Disable for vanilla error messages.
custom-errors: true

# If set to true, this overwrites the /sk and /skript command.
# You can still use /skript:sk while this is enabled.
overwrite-command: true