name: SkriptPlus
version: '${project.version}'
main: me.eren.skriptplus.SkriptPlus
api-version: 1.13
author: eren
website: https://github.com/erenkarakal/SkriptPlus
depend:
  - Skript

commands:
  skriptplus:
    aliases: ["skp"]
    permission: skriptplus.command
